use_frameworks!

platform :ios, '10.0'

target 'SchnorrMusigSDKSwift_Example' do
  pod 'SchnorrMusigSDKSwift', :path => '../'

  target 'SchnorrMusigSDKSwift_Tests' do
    inherit! :search_paths

    
  end
end
